image:
  repository: traefik
  tag: v3.3.3
  pullPolicy: IfNotPresent

# Automatische HTTP → HTTPS Weiterleitung
ports:
  web:
    redirections:
      entryPoint:
        to: websecure  # Weiterleitung auf HTTPS aktivieren

# Let's Encrypt Konfiguration für automatische Zertifikate
additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=tarik.moussa95@gmail.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

# Aktiviert TLS auf Port 443 mit Let's Encrypt
ports:
  websecure:
    tls:
      certResolver: letsencrypt