apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ .Values.environment }}-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          env:
          - name: ENVIRONMENT
            value: "{{ .Values.environment }}"
          - name: SECRET_MESSAGE
            valueFrom:
              secretKeyRef:
                name: site-secret
                key: message
          command: ["sh", "-c"]  # Einfache Shell zum Ersetzen der Platzhalter
          args:
           - echo "<html><body><h1>Hello World!</h1><h2>I am on $ENVIRONMENT  and this is my secret! </h2> <h3>$SECRET_MESSAGE.</h3></body></html>" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'

