image:
  repository: traefik
  tag: v3.3.3
  pullPolicy: IfNotPresent


ports:
  web:
    redirections:
      entryPoint:
        to: websecure  


additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=tarik.moussa95@gmail.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"


ports:
  websecure:
    tls:
      certResolver: letsencrypt

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "128Mi"
