image:
  repository: traefik
  tag: v3.3.3
  pullPolicy: IfNotPresent

# Automatische HTTP → HTTPS Weiterleitung
ports:
  web:
    redirections:
      entryPoint:
        to: websecure  # Weiterleitung auf HTTPS aktivieren


additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=tarik.moussa95@gmail.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--ping"

ping:
  entryPoint: "ping"

ports:
  ping:
    port: 8082
    expose: true
    exposedPort: 8082

healthcheck:
  livenessProbe:
    httpGet:
      path: "/ping"
      port: 8082
    initialDelaySeconds: 3
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: "/ping"
      port: 8082
    initialDelaySeconds: 3
    periodSeconds: 5

service:
  type: LoadBalancer
  loadBalancerIP: "34.141.90.140"

ports:
  websecure:
    tls:
      certResolver: letsencrypt

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "128Mi"
