apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          env:
          - name: ENVIRONMENT
            value: {{ index .Values.environments (.Values.env | default "dev") "environment" | quote }}
          - name: SECRET_MESSAGE
            valueFrom:
              secretKeyRef:
                name: site-secret
                key: message
          command: ["sh", "-c"]  # Einfache Shell zum Ersetzen der Platzhalter
          args:
           - echo "<html><body><h1>Hello World!</h1><p>I am on $ENVIRONMENT. And this is my secret! $SECRET_MESSAGE.</p></body></html>" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'

