apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-test
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Let's Encrypt-Zertifikate holen
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"  # HTTPS aktivieren
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "kub.eulernest.eu"  # Ersetze localhost durch deine echte Domain!
      secretName: tls-secret
  rules:
    - host: "kub.eulernest.eu"  # Ersetze localhost mit deiner Domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80