apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  nginx-{{ .Values.environment }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ingress-ip"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Let's Encrypt-Zertifikate holen
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"  # HTTPS aktivieren
    traefik.ingress.kubernetes.io/router.middlewares: "default-redirect-to-https@kubernetescrd"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"  # Ersetze localhost durch deine echte Domain!
      secretName: "{{ .Values.ingress.tlsSecretName }}"
  rules:
    - host:  "{{ .Values.ingress.host }}"  # Ersetze localhost mit deiner Domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-{{ .Values.environment }}-service
                port:
                  number: 80